// Alphabetisch sortierte Liste aller Berufsfelder
export const allCategories = [
  "Altenpflege",
  "Angehörige der regulären Streitkräfte in sonstigen Rängen",
  "Angehörige gesetzgebender Körperschaften",
  "Arzt- und Praxishilfe",
  "Aus- und Trockenbau, Isolierung, Zimmerei, Glaserei",
  "Bau- und Transportgeräteführung",
  "Bauplanung und -überwachung, Architektur",
  "Berg-, Tagebau und Sprengtechnik",
  "Bestattungswesen",
  "Biologie",
  "Bodenverlegung",
  "Buch- und Kunstantiquitäten, Musikfachhandel",
  "Bühnen- und Kostümbildnerei, Requisite",
  "Büro und Sekretariat",
  "Chemie",
  "Drucktechnik, Buchbinderei",
  "Einkauf und Vertrieb",
  "Elektrotechnik",
  "Energietechnik",
  "Ernährungs- und Gesundheitsberatung",
  "Erziehung, Sozialarbeit, Heilerziehungspflege",
  "Fahr- und Sportunterricht an außerschulischen Bildungseinrichtungen",
  "Fahrzeug-, Luft-, Raumfahrt- und Schiffbautechnik",
  "Fahrzeugführung im Eisenbahnverkehr",
  "Fahrzeugführung im Flugverkehr",
  "Fahrzeugführung im Schiffsverkehr",
  "Fahrzeugführung im Straßenverkehr",
  "Farb- und Lacktechnik",
  "Feinwerk- und Werkzeugtechnik",
  "Fischwirtschaft",
  "Floristik",
  "Forstwirtschaft, Jagdwirtschaft, Landschaftspflege",
  "Fototechnik und Fotografie",
  "Gartenbau",
  "Gastronomie",
  "Gebäudetechnik",
  "Geisteswissenschaften",
  "Geologie, Geografie und Meteorologie",
  "Geschäftsführung und Vorstand",
  "Gesellschaftswissenschaften",
  "Getränkeherstellung",
  "Gewerbe, Gesundheitsaufsicht, Desinfektion",
  "Handel",
  "Hauswirtschaft und Verbraucherberatung",
  "Hochbau",
  "Holzbe- und -verarbeitung",
  "Hotellerie",
  "Human- und Zahnmedizin",
  "IT-Netzwerktechnik, -Administration, -Organisation",
  "IT-Systemanalyse, -Anwendungsberatung und -Vertrieb",
  "Immobilienwirtschaft und Facility-Management",
  "Industrielle Glasherstellung",
  "Industrielle Keramikherstellung",
  "Informatik",
  "Innenarchitektur, Raumausstattung",
  "Kaufleute - Verkehr und Logistik",
  "Klempnerei, Sanitär-, Heizungs- und Klimatechnik",
  "Krankenpflege, Rettungsdienst und Geburtshilfe",
  "Kunsthandwerk und bildende Kunst",
  "Kunsthandwerkliche Keramik- und Glasgestaltung",
  "Kunsthandwerkliche Metallgestaltung",
  "Kunststoff- und Kautschukherstellung",
  "Körperpflege",
  "Lagerwirtschaft, Post und Zustellung, Güterumschlag",
  "Landwirtschaft",
  "Lebensmittel- und Genussmittelherstellung",
  "Leder- und Pelzherstellung",
  "Lehr- und Forschungstätigkeit an Hochschulen",
  "Lehrtätigkeit an allgemeinbildenden Schulen",
  "Lehrtätigkeit an außerschulischen Bildungseinrichtungen",
  "Lehrtätigkeit berufsbildender Fächer und betriebliche Ausbildung",
  "Maler, Stuckateure, Bautenschutz",
  "Maschinenbau- und Betriebstechnik",
  "Mathematik und Statistik",
  "Mechatronik und Automatisierungstechnik",
  "Medien-, Dokumentations- und Informationsdienste",
  "Medizin-, Orthopädie- und Rehatechnik",
  "Medizinisches Laboratorium",
  "Metallbau und Schweißtechnik",
  "Metallbearbeitung",
  "Metallerzeugung",
  "Metalloberflächenbehandlung",
  "Moderation und Unterhaltung",
  "Museumstechnik und -management",
  "Musik-, Gesang-, Dirigententätigkeiten",
  "Musikinstrumentenbau",
  "Naturstein- und Mineralaufbereitung, Baustoffherstellung",
  "Nichtärztliche Therapie und Heilkunde",
  "Objekt-, Personen-, Brandschutz, Arbeitssicherheit",
  "Offiziere",
  "Papier- und Verpackungstechnik",
  "Personalwesen und -dienstleistung",
  "Pferdewirtschaft",
  "Pharmazie",
  "Physik",
  "Polizei- und Kriminaldienst, Gerichts- und Justizvollzug",
  "Produkt- und Industriedesign",
  "Psychologie, nichtärztliche Psychotherapie",
  "Rechnungswesen, Controlling und Revision",
  "Rechtsberatung, -sprechung und -ordnung",
  "Redaktion und Journalismus",
  "Reinigung",
  "Schauspiel, Tanz und Bewegungskunst",
  "Servicekräfte im Personenverkehr",
  "Softwareentwicklung und Programmierung",
  "Speisenzubereitung",
  "Sprach- und Literaturwissenschaften",
  "Steuerberatung",
  "Technische Forschung und Entwicklung",
  "Technische Mediengestaltung",
  "Technische Produktionsplanung und -steuerung",
  "Technischer Betrieb des Eisenbahn-, Luft- und Schiffsverkehrs",
  "Technisches Zeichnen, Konstruktion und Modellbau",
  "Textiltechnik und -produktion",
  "Textilverarbeitung",
  "Theater-, Film- und Fernsehproduktion",
  "Theologie und Gemeindearbeit",
  "Tiefbau",
  "Tiermedizin und Tierheilkunde",
  "Tierpflege",
  "Tierwirtschaft",
  "Tourismus und Sport",
  "Umweltmanagement und -beratung",
  "Umweltschutztechnik",
  "Unternehmensorganisation und -strategie",
  "Unteroffiziere mit Portepee",
  "Unteroffiziere ohne Portepee",
  "Ver- und Entsorgung",
  "Veranstaltungs-, Kamera-, Tontechnik",
  "Veranstaltungsservice und -management",
  "Verkauf (ohne Produktspezialisierung)",
  "Verkauf Bekleidung, Elektro, KFZ, Hartwaren",
  "Verkauf von Lebensmitteln",
  "Verkauf von drogerie- und apothekenüblichen Waren",
  "Verlags- und Medienwirtschaft",
  "Vermessung und Kartografie",
  "Versicherungs- und Finanzdienstleistungen",
  "Verwaltung",
  "Weinbau",
  "Werbung und Marketing",
  "Wirtschaftswissenschaften",
  "Öffentlichkeitsarbeit",
  "Überwachung und Steuerung des Verkehrsbetriebs",
  "Überwachung, Wartung Verkehrsinfrastruktur"
];

// Gruppierung nach Anfangsbuchstaben
export function groupCategoriesByLetter(): Record<string, string[]> {
  const grouped: Record<string, string[]> = {};

  allCategories.forEach(category => {
    const firstLetter = category[0].toUpperCase();
    if (!grouped[firstLetter]) {
      grouped[firstLetter] = [];
    }
    grouped[firstLetter].push(category);
  });

  return grouped;
}

// Verfügbare Buchstaben
export function getAvailableLetters(): string[] {
  const grouped = groupCategoriesByLetter();
  return Object.keys(grouped).sort();
}
